const en = {
  lang: "en",
  langName: "English",
  langCode: "en",
  langIcon: "🇬🇧",
  langDirection: "ltr",

  // Login Page
  signIn: "Sign In",
  accessYourAccount: "Access your account",
  dontHaveAccount: "Don't have an account?",
  signUpNow: "Sign up now",
  emailOrUsername: "Email or Username",
  emailPlaceholder: "you@example.com",
  password: "Password",
  passwordPlaceholder: "••••••••",
  logAsAdmin: "Log as admin",
  adminDescription: "Check this box to access admin features",
  logIn: "Log in",

  // Register Page
  createAccount: "Create Account",
  joinUsToday: "Join us today",
  alreadyHaveAccount: "Already have an account?",
  firstName: "First Name",
  firstNamePlaceholder: "John",
  lastName: "Last Name",
  lastNamePlaceholder: "Doe",
  emailAddress: "Email Address",
  username: "Username",
  usernamePlaceholder: "username",
  dateOfBirth: "Date of Birth",
  confirmPassword: "Confirm Password",

  // Validation Messages
  emailRequired: "Email or username is required",
  invalidEmail: "Please enter a valid email address",
  passwordRequired: "Password is required",
  passwordMinLength: "Password must be at least 6 characters",
  firstNameRequired: "First name is required",
  firstNameMinLength: "First name must be at least 2 characters",
  lastNameRequired: "Last name is required",
  lastNameMinLength: "Last name must be at least 2 characters",
  emailRequiredReg: "Email is required",
  usernameRequired: "Username is required",
  usernameMinLength: "Username must be at least 3 characters",
  usernameInvalid:
    "Username can only contain letters, numbers, and underscores",
  dobRequired: "Date of birth is required",
  dobMinAge: "You must be at least 13 years old",
  dobInvalid: "Please enter a valid date of birth",
  passwordMinLengthReg: "Password must be at least 8 characters",
  passwordLowercase: "Password must contain at least one lowercase letter",
  passwordUppercase: "Password must contain at least one uppercase letter",
  passwordNumber: "Password must contain at least one number",
  confirmPasswordRequired: "Please confirm your password",
  passwordsNotMatch: "Passwords do not match",

  //product Details
  productDetails: "Product Details",
  price: "Price",
  description: "Description",
  addToCart: "Add to Cart",
  addToWishlist: "Add to Wishlist",
  addedToWishlist: "Product added to wishlist!",
  alreadyInWishlist: "Product already in wishlist!",
  wishlistFailed: "Failed to add to wishlist!",
  addedToCartSuccess: "Product added to cart!",
  addToCartFailed: "Failed to add to cart!",
  size: "Size",
  color: "Color",
  home: "Home",
  category: "Category",
};

export default en;
